### ISSUE TITLE
negative unmatched energy

### ISSUE THREAD

**Issue by nick-gorman** [EllieKallmier/ppa_analysis#12]
@EllieKallmier just a reminder to discuss how the unmatched energy is used in the optimisation.

Looks to me like it can go negative in intervals where there is an oversupply of renewables, and this could allow netting off in the unmet_cfe_score constraint. Anyway, just want to check that I'm understanding things correctly.

**Comment by EllieKallmier** [comment]
I think the lower bound in definition of the unmatched variable being set to zero should stop this - the check at the bottom of the function (lines 127-130) should flag whether that variable is being calculated correctly. Let me know if this still isn't looking right to you.
