### ISSUE TITLE
hybrid_shaped Hybrid vs Contracted Energy calc

### ISSUE THREAD

**Issue by nick-gorman** [EllieKallmier/ppa_analysis#14]
The calculation of the 'Hybrid' profile looks very similar to 'Contracted Energy'. 

Why isn't 'Hybrid' just set equal to 'Contracted Energy'?

**Comment by EllieKallmier** [comment]
There's a slight difference between the "generation" traces used for each - 'Contracted Energy' is built from the P90 daily profiles (adjusted at the settlement period) of each generator, where 'Hybrid' uses the same percentages but the actual generated data to look at the 'real' portfolio under the 'optimal' mix.
