### ISSUE TITLE
gen and emissions data loading time

### ISSUE THREAD

**Issue by nick-gorman** [EllieKallmier/ppa_analysis#5]
Running the code to load the generation and emission data seems to take over 10 minutes, even when the cache data has already been downloaded. Probably not ideal from a usability point of view, I'm just imaging someone trying out the tool for the first time and giving up or getting discrated by something else because even loading the data to start testing out the tool takes this long.

**Comment by EllieKallmier** [comment]
@nick-gorman thoughts:
- separate notebook for loading data, save loaded files somewhere for users to reference
- maybe use this as example data too?

**Comment by nick-gorman** [comment]
Implemented caching and separate notebook for adding new data to the cache.
